spring.jpa:
  database: mysql
  hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
  hibernate.ddl-auto: update
  show-sql: true

spring.datasource:
  hikari.maximum-pool-size: 4
  url: jdbc:mysql://localhost:3306/security?serverTimezone=Asia/Seoul
  username: cos
  password: cos1234
  driver-class-name: com.mysql.cj.jdbc.Driver

jwt:
  secret-key: phj-security-with-jwt-study-secret-key
  token-expired-time-ms: 6000000